apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
      - image: divya063/test:filebeat
        imagePullPolicy: ""
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: filebeat-hostpath0
        - mountPath: /var/lib/docker"
          name: filebeat-hostpath1
        - mountPath: /var/run/
          name: filebeat-hostpath2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
        name: filebeat-hostpath0
      - hostPath:
          path: /var/lib/docker
        name: filebeat-hostpath1
      - hostPath:
          path: /var/run/
        name: filebeat-hostpath2
status: {}
